name: Simple Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17  # 這裡改成 17
        uses: actions/setup-java@v1
        with:
          java-version: 17 # 這裡改成 17

      - name: Build Plugin
        run: |
          chmod +x gradlew
          ./gradlew make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyPlugin
          path: builds/*.zip
